### PR TITLE
Make Default Arguments for embed in pages with Interaction as MISSING

### PR DESCRIPTION
**Pull request by Makiyu-py**
## Summary

So I was just randomly helping people in help channels until I stumbled upon [someone asking for help about a weird, internal error](https://discord.com/channels/881207955029110855/881309496385884180/925693314123067392).

Of course, I tried to reproduce it. I did not get that rather odd error, but instead, I got a different one.
```
Ignoring exception in command <discord.commands.SlashCommand name=pager>:
Traceback (most recent call last):
  File ".../pycord/discord/commands/commands.py", line 95, in wrapped
    ret = await coro(arg)
  File ".../pycord/discord/commands/commands.py", line 552, in _invoke
    await self.callback(self.cog, ctx, **kwargs)
  File "test.py", line 26, in pager
    await paginator.send(ctx, ephemeral=False)
  File ".../pycord/discord/ext/pages/pagination.py", line 316, in send
    msg = await ctx.respond(
  File ".../pycord/discord/interactions.py", line 571, in send_message
    payload['embeds'] = [e.to_dict() for e in embeds]
  File ".../pycord/discord/interactions.py", line 571, in <listcomp>
    payload['embeds'] = [e.to_dict() for e in embeds]
AttributeError: 'NoneType' object has no attribute 'to_dict'
```

Here's the Minimal Reproducible Code:
```py
from discord.ext import commands


class PageTest(commands.Cog):
    def __init__(self, bot):
        self.bot = bot

    @slash_command(guild_ids=[...])
    async def pager(self, ctx):
        paginator = pages.Paginator(
            pages=["Page One", "Page Two", "Page Three"],
            show_disabled=False,
            show_indicator=True
        )
        await paginator.send(ctx, ephemeral=False)

bot.add_cog(PageTest(bot))
```

This PR fixes that specific error.
(read the title of this PR for the "specifics" of what I changed)

## Checklist

- [x] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why
- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting, examples, ...)

### CODE REVIEW

**Review by Dorukyum — APPROVED** [review]

**Comment by krittick** [comment]
The current implementation of ext.pages was not meant to be used with the breaking changes introduced in #645 and MISSING was intentionally not used in the original implementation as it caused other errors. Until #656 is merged and the breaking changes reverted, I would suggest not merging anything to ext.pages or else it will need to be reverted back anyway.

**Comment by Lulalaby** [comment]
Setting as planned backlog task

**Comment by krittick** [comment]
I'm going to close this as it no longer applies after the rework done in #629.
