### ISSUE TITLE
Paginator broke with Update to v2.7.0

### ISSUE THREAD

**Issue by Miner1e** [Pycord-Development/pycord#3064]
### Summary

Using PageGroups in a Paginator on v2.7.0 results in: discord.errors.ApplicationCommandInvokeError: Application Command raised an exception: AttributeError: 'Page' object has no attribute 'label'

### Reproduction Steps

After updating to v2.7.0 my commands using PageGroups inside a Paginator started throwing the following Error:
```
Traceback (most recent call last):
  File "...site-packages\discord\commands\core.py", line 138, in wrapped
    ret = await coro(arg)
          ^^^^^^^^^^^^^^^
  File "...site-packages\discord\commands\core.py", line 1108, in _invoke
    await self.callback(ctx, **kwargs)
  File "{botLocation}main.py", line 140, in test
    await commands.test(ctx, arg)
  File "{botLocation}features\commands.py", line 18, in test
    await Paginator(pages=[PageGroup(pages=["hi", "hit", "wah"], label="thing"), PageGroup(pages=["fi", "fit", "fah"], label="thinfdg")], show_menu=True).respond(ctx.interaction)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...site-packages\discord\ext\pages\pagination.py", line 455, in __init__
    self.add_menu()
  File "...site-packages\discord\ext\pages\pagination.py", line 752, in add_menu
    self.menu = PaginatorMenu(self.page_groups, placeholder=self.menu_placeholder)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...site-packages\discord\ext\pages\pagination.py", line 1274, in __init__
    opts = [
           ^
  File "...site-packages\discord\ext\pages\pagination.py", line 1276, in <listcomp>
    label=page_group.label,
          ^^^^^^^^^^^^^^^^
AttributeError: 'Page' object has no attribute 'label'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "...site-packages\discord\bot.py", line 1154, in invoke_application_command
    await ctx.command.invoke(ctx)
  File "...site-packages\discord\commands\core.py", line 435, in invoke
    await injected(ctx)
  File "...site-packages\discord\commands\core.py", line 146, in wrapped
    raise ApplicationCommandInvokeError(exc) from exc
discord.errors.ApplicationCommandInvokeError: Application Command raised an exception: AttributeError: 'Page' object has no attribute 'label'
```
I then, to debug, created a short piece of code still throwing the same error and went back to v2.6.1 where it worked.

To reproduce:
Go to v2.6.1 and run the Minimal Reproducible Code and find out, that the Paginator sends perfectly
Update to release v2.7.0 (Or current newsest commit of master 128a172) and be faced with the error aboth

I originally opened a [thread](https://discord.com/channels/881207955029110855/1461014718473830596) in your discord thinking, this might be my fault but we werent able to find an error with my code so we assumed, this must be an issue with release 2.7.0

### Minimal Reproducible Code

```python
await Paginator(pages=[PageGroup(pages=["hi", "hit", "wah"], label="thing"), PageGroup(pages=["fi", "fit", "fah"], label="thinfdg")], how_menu=True).respond(ctx.interaction)
```

### Expected Results

The Minimal Reproducible Code should send the same Paginator message in v2.7.0 as in v2.6.1

### Actual Results

The Minimal Reproducible Code crashes with the following error message: `discord.errors.ApplicationCommandInvokeError: Application Command raised an exception: AttributeError: 'Page' object has no attribute 'label'` on 2.7.0

### Intents

Not relevant but: intents=discord.Intents.all()

### System Information

```bash
- Python v3.11.1-final
- py-cord v2.7.None-final
- aiohttp v3.11.13
- system info: Windows 10 10.0.26200
```

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### Additional Context

I was reading through some of the source Code of the Paginator Object and found, that in [Line 430](https://github.com/Pycord-Development/pycord/blob/master/discord/ext/pages/pagination.py?plain=1#L430) of the Paginator, the pages field gets assigned to the result of get_page_group_content() which appears to only return a list of Page objects, which obviosly don't have the label field from the original PageGroup object anymore. After that, the Paginator loops through those pages and tries to get their label field, which doesnt exist anymore.

Im not familliar with this codebase at all and didnt spend too much time understanding this part, but maybe this insight helps understanding, what's going wrong.

**Comment by Paillat-dev** [comment]
Fixed in #3065
