### PR TITLE
Add missing **kwargs param to support non-explicit parameters in `SlashCommandGroup` (fixes issue introduced by #1127)

### PR DESCRIPTION
**Pull request by krittick**
## Summary

#1127 fixed an issue by allowing keyword arguments to be accepted, but it also inadvertently removed the **kwargs parameter that is still needed for other variables in the class (e.g. `check`).

Specifically, this error is fixed by this PR:

`TypeError: SlashCommandGroup.__init__() got an unexpected keyword argument 'checks'`

## Checklist

- [x] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why
- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting, examples, ...)

### CODE REVIEW

**Comment by Dorukyum** [comment]
Apparently checks are passed somewhere but the `__init__` doesnt set them, which is why I missed this when approving the other pr.

**Comment by krittick** [comment]
Yeah, and this PR didn't fix it properly because I missed that too. I reverted this already.

**Comment by Dorukyum** [comment]
> Yeah, and this PR didn't fix it properly because I missed that too. I reverted this already.

👍
