### PR TITLE
feat: Implements positional flags

### PR DESCRIPTION
**Pull request by Vioshim**
## Summary

This allows FlagConverters to be used after the first text expression, for example

```py
class HandleText(FlagConverter, prefix="--", delimiter=" "):
    text: str = commands.flag(positional=True)
    flip: bool = False
    
@bot.bridge_command()
async def welcome(ctx: bridge.BridgeContext, *, flags: HandleText):
    text = flags.text[::-1] if flags.flip else flags.text
    await ctx.respond(text)

# ?welcome Hello world
# ?welcome Hello world --flip True
# ?welcome --text Hello world
# ?welcome --text Hello world --flip True
```

## Information

- [ ] This PR fixes an issue.
- [X] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed).
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting,
      examples, ...).

## Checklist

- [X] I have searched the open pull requests for duplicates.
- [X] If code changes were made then they have been tested.
  - [X] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why.
- [ ] I have updated the changelog to include these changes.

### CODE REVIEW

File: discord/ext/commands/flags.py [hunk 1]
```diff
@@ -277,6 +293,7 @@ class FlagsMeta(type):
         __commands_flag_case_insensitive__: bool
         __commands_flag_delimiter__: str
         __commands_flag_prefix__: str
+        __commands_flag_positional__: Flag | None
```
Comment (Dorukyum) [inline discord/ext/commands/flags.py:296]: None of the other attributes are typed as optional, could we try to keep that up?

File: docs/ext/commands/commands.rst [hunk 2]
```diff
@@ -656,6 +656,19 @@ This tells the parser that the ``members`` attribute is mapped to a flag named `
 the default value is an empty list. For greater customisability, the default can either be a value or a callable
 that takes the :class:`~ext.commands.Context` as a sole parameter. This callable can either be a function or a coroutine.
 
+Flags can also have one of its flags be marked as positional. This means that the flag does not require a corresponding
```
Comment (JustaSqu1d) [inline docs/ext/commands/commands.rst:659]:
```suggestion
Flags can also be positional. This means that the flag does not require a corresponding
```

**Review by JustaSqu1d — CHANGES_REQUESTED** [review]

File: CHANGELOG.md [hunk 3]
```diff
@@ -24,6 +24,8 @@ These changes are available on the `master` branch, but have not yet been releas
   ([#2421](https://github.com/Pycord-Development/pycord/pull/2421))
 - Added `member` data to the `raw_reaction_remove` event.
   ([#2412](https://github.com/Pycord-Development/pycord/pull/2412))
+- Added `positional` argument to `commands.Flag`
```
Comment (Dorukyum) [inline CHANGELOG.md:27]:
```suggestion
- Added `positional` argument to `commands.Flag`.
```

File: discord/ext/commands/flags.py [hunk 4]
```diff
@@ -82,6 +82,8 @@ class Flag:
     max_args: :class:`int`
         The maximum number of arguments the flag can accept.
         A negative value indicates an unlimited amount of arguments.
+    positional: :class:`bool`
+        Whether the flag is positional or not. There can only be one positional flag.
```
Comment (Dorukyum) [inline discord/ext/commands/flags.py:86]:
```suggestion
        Whether the flag is positional.
        A :class:`FlagConverter` can only handle one positional flag.
```

File: docs/ext/commands/commands.rst [hunk 5]
```diff
@@ -656,6 +656,19 @@ This tells the parser that the ``members`` attribute is mapped to a flag named `
...
+For example, in the following code:
+
+.. code-block:: python3
+
+    class BanFlags(commands.FlagConverter):
+        members: List[discord.Member] = commands.flag(name='member', positional=True)
+        reason: str = commands.flag(default='no reason')
+        days: int = commands.flag(default=1)
+
+The ``members`` flag is marked as positional, meaning that the user can invoke the command without specifying the flag
```
Comment (Dorukyum) [inline docs/ext/commands/commands.rst:670]:
```suggestion
The ``members`` flag is marked as positional, meaning that the user can invoke the command without explicitly specifying the flag.
```

**Review by Dorukyum — CHANGES_REQUESTED** [review]

**Comment by Lulalaby** [comment]
@Vioshim please work on dorus comment and resolve conflcts

File: discord/ext/commands/flags.py (hunk 1 above)
Comment (Vioshim) [reply discord/ext/commands/flags.py:297]: My bad for the delay have gotten busy, do you mean as in, using Optional[Flag] or simply using Flag instead ?

**Comment by Paillat-dev** [comment]
I have no idea how this works, but if the only thing stopping it from getting merged are conflicts, I can sure resolve those.

**Comment by Lulalaby** [comment]
@Pycord-Development/contributors can we get some testing here :D

**Review by Paillat-dev — CHANGES_REQUESTED** [review]
```
File "C:\Users\Jérémie\Documents\GitHub\pycord\thing.py", line 23, in <module>
    class BasicText(FlagConverter, prefix="--", delimiter=" "):
  File "C:\Users\Jérémie\Documents\GitHub\pycord\thing.py", line 24, in BasicText
    text: str = flag(positional=True)
                ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jérémie\Documents\GitHub\pycord\discord\ext\commands\flags.py", line 143, in flag
    return Flag(
           ^^^^^
TypeError: Flag.__init__() got an unexpected keyword argument 'name'
```

The error does not seem to be caused by this PR, but rather by me using python `3.11`. The error is not present in my testing when using python `3.10`.

fix in #2759 

Other than that, this seems to work to me, although I don't think I'm experienced enough with flags - and prefixed commands to assess with good certainty that everything works as expected.

**Comment by Lumabots** [comment]
does this need testing or is it ready to merge ?

**Comment by Paillat-dev** [comment]
Needs testing + doesn't work with python 3.11+

**Comment by Lulalaby** [comment]
Merge conflicts

**Comment by Paillat-dev** [comment]
@Lulalaby I think that OP is gone but I can fix these in a new pr. Lmk if ok

**Comment by Lulalaby** [comment]
Sure go for it if you still think it's a good addition

**Comment by Vioshim** [comment]
My apologies, felt lost on how to be able to contribute in the project once i saw the things about merging conflicts or the documentation changes, so ended up lost on how to correct it alongside irl stuff, so my apologies for the lack of response

**Comment by Paillat-dev** [comment]
@Vioshim no worries. Do you still want to work on this ? If lmk and I'll handle the merge conflicts and the rest

**Comment by Vioshim** [comment]
That'd be quite appreciated, thank you!!
@Paillat-dev

**Comment by Paillat-dev** [comment]
No worries and thank you for your contribution !

**Comment by Paillat-dev** [comment]
@Lumabots Can I get some testing from you ? Specifically on python 3.11 and higher ?

File: discord/ext/commands/flags.py [hunk 6]
```diff
@@ -95,6 +98,7 @@ class Flag:
     annotation: Any = _missing_field_factory()
     default: Any = _missing_field_factory()
     max_args: int = _missing_field_factory()
+    positional: bool = _missing_field_factory(
```
Comment (Paillat-dev) [inline discord/ext/commands/flags.py]:
```suggestion
    positional: bool = _missing_field_factory()
```

**Comment by Lumabots** [comment]
> @Lumabots Can I get some testing from you ? Specifically on python 3.11 and higher ?

Yep doing that tomorrow evening

**Review by DA-344 — APPROVED** [review]
lgtm code wise, if this is tested and works then should be ready to merge

**Comment by Lulalaby** [comment]
Damn one year old already
